sysdig_api_token: <your api token>
region: <Your sysdig region> #Check https://docs.sysdig.com/en/docs/administration/saas-regions-and-ip-ranges/ for reference
fileName: <file name of the csv report, date will be added>
output_path: <output file you want to save your report csv file>
query: | #You can add here your sysql query